export default {
  LOGO: require('../assets/images/logo.png'),
  CLC_LOGO: require('../assets/images/vn_clc.png'),
  LOGO_BORDER: require('../assets/images/logo_border.png'),
  LOGO_TEXT: require('../assets/images/logo_text.png'),
  NO_AVATAR: require('../assets/images/no-avatar.png'),
  HEADER_SIDEBAR: require('../assets/images/Header.jpg'),
  BACKGROUND: require('../assets/images/background.png'),
  BACKGROUND_LOGIN: require('../assets/images/bg.png'),
  INFO: require('../assets/images/icon/info.png'),
  INFO_SHADOW: require('../assets/images/icon/info_shadow.png'),
  CUSTOMER: require('../assets/images/icon/customer.png'),
  CUSTOMER_SHADOW: require('../assets/images/icon/customer_shadow.png'),
  PACKAGING: require('../assets/images/icon/packeging.png'),
  PACKAGING_SHADOW: require('../assets/images/icon/packeging_shadow.png'),
  TRANSITION: require('../assets/images/icon/transition.png'),
  TRANSITION_SHADOW: require('../assets/images/icon/transition_shadow.png'),
  REPORT: require('../assets/images/icon/info.png'),
  REPORT_SHADOW: require('../assets/images/icon/info_shadow.png'),
  KITCHEN: require('../assets/images/icon/kitchen.png'),
  KITCHEN_SHADOW: require('../assets/images/icon/kitchen_shadow.png'),
  PERMISSION: require('../assets/images/storage-box-icon-5.jpg'),
  ERROR: require('../assets/images/error.png'),
};